### ISSUE TITLE
Error when trying init.lua for neovim

### ISSUE THREAD

**Issue by flo8** [omerxx/dotfiles#1]
Hi @omerxx 

First of all, thank you very much for the useful videos on Youtube regarding Golang and Neovim. I wanted to try your init.lua and got the following errors (version of neovim 0.9.1 installed on Fedora 38).

Error detected while processing /root/.config/nvim/init.lua:
Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:86: Parser not available for language "help"
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to add a new parser!
sumneko_lua is deprecated, use lua_ls instead.
This feature will be removed in lspconfig version 0.2.0
fidget.nvim will soon be rewritten. Please checkout the 'legacy' tag to avoid breaking changes.
E5113: Error while calling lua chunk: /root/.config/nvim/init.lua:586: attempt to call field 'setup' (a nil value)
stack traceback:
        /root/.config/nvim/init.lua:586: in main chunk
Error detected while processing /root/.config/nvim/plugin/packer_compiled.lua:
E5112: Error while creating lua chunk: /root/.config/nvim/plugin/packer_compiled.lua:1: unexpected symbol near '1'

Did I miss something?

**Comment by omerxx** [comment]
Hi! I feel like I've seen this comment on of the YT videos? :)
In any case, I suggest taking the bits that interest you and build up slowly as the errors show missing prerequisits.
I'm in the transition of moving from packer to lazy so I highly recommend checking this out as well!
