### ISSUE TITLE
Sketchybar does not open to the right

### ISSUE THREAD

**Issue by ChrisGVE** [omerxx/dotfiles#23]
I am using your configuration for sketchybar, I am using the latest version, still sketchybar opens on the top but not on the right. Any suggestion what I could do to troubleshoot this?
Btw the documentation of sketchybar does not mention that position can be put to the right, maybe it is outdated.
Thanks for the help

**Comment by dkelll** [comment]
@ChrisGVE What did you do to fix this (I realize it's a year later, no worries if you don't recall)?

**Comment by dkelll** [comment]
> [@ChrisGVE](https://github.com/ChrisGVE) What did you do to fix this (I realize it's a year later, no worries if you don't recall)?

@ChrisGVE Ignore, I solved it 🤘🏻
