### ISSUE TITLE
Transparent tmux statusbar

### ISSUE THREAD

**Issue by jdrupal-dev** [omerxx/dotfiles#3]
Hi.
How did you manage to make the tmux statusbar transparent in your latest video?
I copied your exact tmux config, but my statusbar is dark gray.

**Comment by migueltc13** [comment]
Check out my fork of catppuccin theme that addresses this:
- [catppuccin-tmux](https://github.com/migueltc13/catppuccin-tmux/)
- My [.tmux.conf](https://github.com/migueltc13/dotfiles/blob/main/.tmux.conf)

![Screenshot from 2023-12-31 22-27-33](https://github.com/omerxx/dotfiles/assets/73550106/3dca88ab-d5d9-4c9d-9170-127c8d9f8732)

**Comment by jdrupal-dev** [comment]
Yes thanks. It works great.

**Comment by jdrupal-dev** [comment]
Yes, thank you. Your fork works great.
