### ISSUE TITLE
Why do you use screen-254color on tmux?

### ISSUE THREAD

**Issue by bavulapati** [omerxx/dotfiles#4]
https://github.com/omerxx/dotfiles/blob/6beb165acb2141cbcf1577a369d1205a8bb333f6/tmux/tmux.conf#L2C33-L2C48

What's the impact?

**Comment by bavulapati** [comment]
Not sure if this is right place to ask?
I'm reading your tmux configuration and did not find much about 254 colour on the internet.

**Comment by JZsmitty** [comment]
This is likely a typo, or was possibly copied from a config somewhere that had this value. The only terminal colors I know of are 8, 16, 88, and 256. Tmux itself suggests that you only ever set the default value to screen-256color in its documentation.

Please see the TMUX fax here, which covers this exact setting.
https://github.com/tmux/tmux/wiki/FAQ

**Comment by JZsmitty** [comment]
> Not sure if this is right place to ask? I'm reading your tmux configuration and did not find much about 254 colour on the internet.

This is likely a typo, or was possibly copied from a config somewhere that had this value. The only terminal colors I know of are 8, 16, 88, and 256. Tmux itself suggests that you only ever set the default value to screen-256color in its documentation.

Please see the TMUX fax here, which covers this exact setting.
https://github.com/tmux/tmux/wiki/FAQ

**Comment by bavulapati** [comment]
thanks @JZsmitty
