### ISSUE TITLE
Suggestion: Use .stowrc

### ISSUE THREAD

**Issue by ConductiveFoam** [omerxx/dotfiles#6]
Just came about your repository and wanted to suggest using the [Stow resource file](https://www.gnu.org/software/stow/manual/html_node/Resource-Files.html) as I think it's just free ergonomics

**Comment by omerxx** [comment]
Interesting!
This is just a preconfigured rc file for stow that can sit in the repo?
That's the idea?

**Comment by ConductiveFoam** [comment]
Exactly, you put it in the directory from where you usually execute stow. [See this example from my old dotfiles](https://github.com/ConductiveFoam/dotfiles-old/blob/master/.stowrc): I specify the target and `--no-folding` because I realized that I wrote out those two for almost all invocations anyway.

**Comment by omerxx** [comment]
Thanks!
